ROTOR_P_X: 0.10
ROTOR_P_Y: 0.10
DATASET_S: 2000
DATASET_LENS: 16000
P_THRUST_SIGMA: 0.1
UNMODEL_THRUST_SIGMA: 0.05
ENABLE_DRAG: TRUE
ENABLE_I:    TRUE

ROOT_PATH: ../data/blackbird/ampersand/yawForward/maxSpeed2p0
POSE_FILE: ../data/quad13/pose_2024-02-21-13-45-50.txt
RSM_FILE: ../data/quad13/rsm_2024-02-21-13-45-50.txt
# ROOT_PATH: ../data/blackbird/ampersand/yawConstant/maxSpeed3p0
# ../data/blackbird/pacasso/yawForward/maxSpeed4p0

